FROM python:3.8.5-slim
LABEL version=0.1.0 \
      metadata="The base image for calorie counter code" \
      maintainer="Volodymyr Yahello <vyahello@gmail.com>"
RUN pip install --no-cache-dir --upgrade pip && \
    apt-get update && \
    apt-get autoclean -y
